### ISSUE TITLE
Bigger Lobby doesnt support v45 with players over 8 players

### ISSUE THREAD

**Issue by PS2ClassicsVault** [legoandmars/BiggerLobby#13]
Players that join immediately crashes the lobby

**Comment by legoandmars** [comment]
Can I get some more background info?
1) What other mods are you using, if any?
2) What player count are you setting your lobby to?
3) Are you using the latest version (2.5.0)?


It would also be a huge help to get a log to see if anything specific is going on. Should be located in `BepInEx/LogOutput.log` - you just drag the file directly into the GitHub text box.

If you're using a mod manager, you can access your BepInEx folder by going here:

![image](https://github.com/legoandmars/BiggerLobby/assets/34404266/85be2932-bfb8-4edd-8d44-b2bee74497e5)

**Comment by PS2ClassicsVault** [comment]
![Screenshot (5)](https://github.com/legoandmars/BiggerLobby/assets/118215758/d126cfe3-1c59-46fc-8913-32548e34109c)
when i host 8players it gives me this error
[LogOutput.log](https://github.com/legoandmars/BiggerLobby/files/13641653/LogOutput.log)

**Comment by legoandmars** [comment]
This looks like it could be a problem with LateCompany

**Comment by PS2ClassicsVault** [comment]
> This looks like it could be a problem with LateCompany

So i should submit it to the late company github?
