### ISSUE TITLE
BiggerLobby no longer working with 5+ people on v40

### ISSUE THREAD

**Issue by mindofbrandon** [legoandmars/BiggerLobby#14]
Stack trace also present in v2.5.0

# Stack Trace in console when loading up game
`[Info   :   BepInEx] Loading [BiggerLobby 2.6.0]
[Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type SteamLobbyManager and name loadLobbyListAndFilter and parameters
[Error  : Unity Log] ArgumentException: Undefined target method for patch method static System.Collections.IEnumerator BiggerLobby.Patches.NonGamePatches::LoadLobbyListAndFilter(System.Collections.IEnumerator result, SteamLobbyManager __instance)
Stack trace:
HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Rethrow as HarmonyException: Patching exception in method null
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
BiggerLobby.Plugin.Awake () (at <fef7f63cf8a640b1b940472bdde3e07d>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()`

## List of mods 

299792458-MoreMoneyStart-2.0.0
Barnyard_Boys-KeepItemTp-1.0.0
Suskitech-AlwaysHearActiveWalkies-1.4.2
66Studios-No_Weight_Gain-1.0.0
bizzlemip-BiggerLobby-2.6.0
matsuura-HealthMetrics-1.0.2
Pooble-LCBetterSaves-1.4.0
FlipMods-BetterStamina-1.2.1
RickArg-Helmet_Cameras-2.1.3
Blorb-WeatherMultipliers-1.0.0
Sligili-More_Emotes-1.1.2
2018-LC_API-2.1.2
bizzlemip-NoPenalty-1.0.1
Renegades-FlashlightToggle-1.3.1
BepInEx-BepInExPack-5.4.2100
x753-More_Suits-1.3.3
Chrispacito-Longnose_Anime_Suits-1.0.1
Vibrant-BadGojoSuit-1.0.1
Drakorle-MoreItems-1.0.1
larryr1-LukesAdditionalSuits-1.0.3
anormaltwig-LateCompany-1.0.4
RugbugRedfern-Skinwalkers-2.0.0
MoreLethal-Pinger-3.2.0
alexanderjoe-BiggeryBattery-1.0.2
FlipMods-ReservedItemSlotCore-1.4.4
FlipMods-ReservedFlashlightSlot-1.4.5
FlipMods-ReservedWalkieSlot-1.4.6
Sant5050-ShopkeeperNoWait-1.0.1
amnsoft-EmployeeAssignments-1.0.3
tinyhoot-ShipLoot-1.0.0
Sligili-HDLethalCompany-1.5.3
[LogOutput.log](https://github.com/legoandmars/BiggerLobby/files/13655641/LogOutput.log)

**Comment by mindofbrandon** [comment]
downgraded to 2.4.0 as this does not show stack trace and runs as desired

**Comment by legoandmars** [comment]
This is intentional, some code changed in v45 that made them incompatible

**Comment by legoandmars** [comment]
If it becomes a massive problem, and there's a lot of people still on v40, I could look into an update that has compatibility for both

But I would prefer to avoid it if possible

**Comment by mindofbrandon** [comment]
Understandable, thanks
