### ISSUE TITLE
[SUGGESTION] Mod Checker

### ISSUE THREAD

**Issue by Fenish** [legoandmars/BiggerLobby#18]
I suggest implementing a Mod Checker feature to enhance user experience by providing clear information on missing mods during join errors. This feature would display a modlist or specifically highlight which mod is missing, aiding users in resolving compatibility issues efficiently.

Because when 1 or 2 mod is missing join error will be "An Error Occured" but its not detailed. Im sure that is because of missing mod.
Most players using bigger lobby for play with strangers.

**Comment by Fenish** [comment]
If its possible to get mod list it would be nice to implement this mechanic

**Comment by legoandmars** [comment]
I do think this needs to exist, but I think it's a bit out of scope for this mod specifically.

Ideally it would be added to something like LC_API or a compatibility check library. The closest thing right now is (CompatibilityChecker)[https://thunderstore.io/c/lethal-company/p/Ryokune/CompatibilityChecker/]
