### ISSUE TITLE
incompatible version

### ISSUE THREAD

**Issue by kezzkezzkezz** [legoandmars/BiggerLobby#21]
![image](https://github.com/legoandmars/BiggerLobby/assets/60633244/b12b3d6f-10cd-4d34-bfd4-2aa4e98d820b)
Updated to Version 1.3.11 of LethalExpansion and now BiggerLobby is broken

**Comment by kezzkezzkezz** [comment]
Running BiggerLobby Version 2.6.0

**Comment by legoandmars** [comment]
fixed in 2.7.0
