### ISSUE TITLE
broken end stats. lvl up from LEADER to BOSS broken.

### ISSUE THREAD

**Issue by Seathroath** [legoandmars/BiggerLobby#23]
was unable to lvl up from LEADER to BOSS. I went to 500 exp in leader and its just stays that way. If i get any more exp the title disappears and its just spams the full lvl sounds.

**Comment by legoandmars** [comment]
Can you give a list of mods you have installed? Should be able to export a profile code if you use r2modman

**Comment by Seathroath** [comment]
![rank](https://github.com/legoandmars/BiggerLobby/assets/155325019/50369829-71a7-460a-be89-c3fc64bd9277)

it spams that image and makes the sound like i lvled up 4+ time.

heres my profile
018ceb45-249d-4fda-4403-9064d1bb836e

**Comment by Seathroath** [comment]
i disabled all my mod but [2018-LC_API] [BepInEx-BepInExPack] and biggerlobby. and im still getting this bug.

**Comment by dopadream** [comment]
also getting this

**Comment by legoandmars** [comment]
fixed in 2.7.0
