### ISSUE TITLE
can we remove crazydude12 for less clutter?

### ISSUE THREAD

**Issue by Seathroath** [legoandmars/BiggerLobby#24]
can we remove crazydude12 for less clutter?
I'm supposing that's a place holder for something, but it fills up the sides of my report screen.

**Comment by legoandmars** [comment]
Hmm, that shouldn't be displaying

How many people are you playing with? Are you on a manual install or using a mod manager

**Comment by Seathroath** [comment]
Just me playing online.  I used r2modmanager to install and run. But I believe it still said that when others in the lobby too.

**Comment by legoandmars** [comment]
Does the player list seem to work properly otherwise? Like it'll still display all the players, it'll just say Crazydude12 in empty slots?

**Comment by Seathroath** [comment]
![crazy dude 12](https://github.com/legoandmars/BiggerLobby/assets/155325019/29b3bbb4-8957-4da3-8f02-94946d047033)

here is what it looks like.

**Comment by legoandmars** [comment]
It seems like you have both BiggerLobby and MoreCompany installed. As-is, these mods wont work with each other. You'll have to uninstall one.

**Comment by Seathroath** [comment]
> It seems like you have both BiggerLobby and MoreCompany installed. As-is, these mods wont work with each other. You'll have to uninstall one.

I had no idea. It was just a mod i needed for some cosmetics mods. will see if i can get rid of it thanks!
