### ISSUE TITLE
Fraudulent Thunderstore Mod

### ISSUE THREAD

**Issue by mitcho2013** [legoandmars/BiggerLobby#25]
Beware the uploader Splinter on Thunderstore. They've uploaded a seemingly duplicate BiggerLobby around yesterday's patch (01/08). Since Thunderstore by default searches by latest update date, it is the current (as of posting) top search result on the mod platform for "BiggerLobby". Installing this version of BiggerLobby and its dependencies will cause parts of gameplay to become non-functional including the Scanner. 

There does not appear to be a built-in report function on the Thunderstore site, so I will paste the link to the fraudulent upload here in case anyone else has any resources they can use against this uploader: https://thunderstore.io/c/lethal-company/p/Splinter/BiggerLobby/.

![splinter_fraud](https://github.com/legoandmars/BiggerLobby/assets/126298589/2ef084bc-2bba-4192-8ad6-795f40765c61)

**Comment by legoandmars** [comment]
It's been removed - for future reference you can always report these in the #thunderstore-issues channel in the [Lethal Company Modding Discord](https://discord.com/invite/lcmod)
