### ISSUE TITLE
Injecting/Mentioning player name via [playerNum0] in the in-game chat doesn't work

### ISSUE THREAD

**Issue by TIRTAGT** [legoandmars/BiggerLobby#28]
During developing a plugin that offers Player Username even on LAN lobby, after testing compatibility with BiggerLobby, I noticed that my plugin and ***even*** the game can't refer/mention the lobby hoster (Player #0) in the chat, this issue is still valid on setup with only LC_API + BiggerLobby enabled.

Here are screenshots showing what happened if I try to mention `Player #1`, `Player #0`, and `Player #2` on the chat system:
![Screenshot_19-59_04-02-2024](https://github.com/legoandmars/BiggerLobby/assets/55649705/55a37ada-9ba6-4ad8-ba4d-2e97935879a0)

As visible on the picture, it seems like the `Player #0` is not evaluated to an actual player username, which in my case is `TIRTAGT`.

----

After forking and checking BiggerLobby's source code, the issue seems to be just because of [wrong starting array Index on Patches/InternalPatches.cs line 38](https://github.com/legoandmars/BiggerLobby/blob/73e2e916e0385497b54181c612d396a99242e6b8/Patches/InternalPatches.cs#L38)

I [patched the code](https://github.com/TIRTAGT/BiggerLobby/commit/40ed4c6212aa99ba302111c6be25e82b6be53ddd), and here's the result doing the above test again:
![Screenshot_20-04_04-02-2024](https://github.com/legoandmars/BiggerLobby/assets/55649705/cc19ebbc-0f00-4d00-af15-ddffad861ac0)

----

Issue fixed, As the needed changes to fix the issue is minimal, I'm not sure whether or not to open a Pull Request for this, so I've open up an issue instead.

Let me know if I need to open a Pull Request [for the fix](https://github.com/TIRTAGT/BiggerLobby).

**Comment by legoandmars** [comment]
appreciate it, I went ahead and fully rewrote the method since it was causing problems with LethalExpansion

should be fixed in 2.7.0
