### ISSUE TITLE
cant use scanner and I dont see the circle thing when you interact with door for example

### ISSUE THREAD

**Issue by serekAlmette** [legoandmars/BiggerLobby#7]
I dont have any mods turned on besides LC_API, BIggerLobby and BepInExPack but i still cant see neither scanner nor circle thing when you interact with something

**Comment by legoandmars** [comment]
Are you sure you're using the latest version (2.4.0)?

**Comment by 1tsm3ga** [comment]
I can confirm that the issue is on v2.4.0, scanner is non-functional and interact hold circle is not visible, although the function works.
