### ISSUE TITLE
Enabling mod causes the day-end report and experience progress to not display

### ISSUE THREAD

**Issue by LeoCai12777** [legoandmars/BiggerLobby#9]
Steps to reproduce:
Using r2modman, import the mod profile using code 018c406e-d9d1-22df-cda4-3629be35e1a3
Alternatively, download and enable mods 
  "BepInExPack" by BepInEx, 
  "LC_API" by 2018,
  "BiggerLobby" by bizzlemip
  
Launch modded game using "Start modded" button in r2modman
Host a new lobby and enter the game
Land the ship
Once ship lands, start the ship to end the day

Expected: Day-end grade report shows up (something similar to below)
![image](https://github.com/legoandmars/BiggerLobby/assets/29362004/460f57c7-f10c-4070-8581-764dff88cc72)

Actual: The report does not display and the game progresses to the next day

**Comment by legoandmars** [comment]
This should be fixed in 2.6.0
If anybody runs into issues with the end stats screen, feel free to mention them on this issue
